gravitl/netmaker-docs

- server-installation.rst
Updated the example nginx reverse proxy config with the one I've had success with.
> Updated nginx proxy config for Netmaker

- troubleshoot.rst
Adding -udpholepunch no which fixed me up
> Proposed to add for VPS running Netmaker in Docker on that host

- server-installation.rst
Otherwise it will break Caddy config.
> Remove unnecessary trailing slashes

- quick-start.rst
- upgrades.rst
added upgrade steps to v0.16.1 for MQ changes and added steps to quickstart for v0.16.1
> changes to upgrades and quickstart

- conf.py
> version number

- quick-start.rst
moves mq section above the install netmaker section
> mq switcharoo

- troubleshoot.rst
Add fix for Fyne error when running Windows Netclient
> Troubleshooting fyneerror

- server-installation.rst
updates to the baremetal docs to use the dynamic mq after v0.16.1
> updates to no docker install

- advanced-client-install.rst
- conf.py
- netclient.rst
- troubleshoot.rst
Notes & Details for Netclient install details for OpenWRT.
> Adding OpenWRT netclient install details

- Dockerfile
Adding support for sphinx Make document and publish it through nginx in Dockerfile.
Already tested.
> Improvement in Dockerfile to make and test

- api.rst
- server-installation.rst
- Remove Markdown
- Fix link
- Remove examples
> Update API documentation

- conf.py
- upgrades.rst
> add upgrade steps for v0.18.5

- quick-start.rst
added firewall rules
added missing dns entries
updated manual installation to reflect latest changes. did a test run of copy/pasting commands from the page and server runs great.
> Net 139 install updates

- netclient.rst
fixed windows and darwin installer links.
> fixed netclient installer links

- install.rst
- ui-reference.rst
> Kwesi/net 405 UI enable white labelling

- ui-reference.rst
merge after https://github.com/gravitl/netmaker-docs/pull/162
> Kwesi/net 429 add ability to change colors in ee UI

- netclient.rst
removed netclient docker environment variables. no longer relevant
> Net 418 client docker

- pro/index.rst
- pro/pro-users.rst
- pro/rac.rst
> docs: add section for RAC, with installation steps

- pro/index.rst
- pro/pro-users.rst
- pro/rac.rst
* docs: add section for RAC, with installation steps
* darwin/windows instructions
* docs: address comments
* run as sudo instructions
* docs: address comments
* mac run as sudo
* mac command change
---------
> docs: add section for RAC, with installation steps (#219)

- pro/rac.rst
> docs(NET-701): add notes on opengl dep and VMs

- license.rst
- support.rst
updated license.rst to mention apache license instead of sslp and removed sslp explanation from support.rst
> remove sslp license and change to apache

- architecture.rst
additional coredns setup instruction
> Addtnl coredns instruction

- netclient.rst
https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/956
> removed-freebsd-install-instructions
